// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU4hVQ63CXfQPrjoj9fUGg4uN-C8pJ7HQ',
    appId: '1:849111596971:web:cd8369566aca392c7e1cee',
    messagingSenderId: '849111596971',
    projectId: 'my-saathi-app',
    authDomain: 'my-saathi-app.firebaseapp.com',
    storageBucket: 'my-saathi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxS8eIhu9lGhJtE5zHGZKFbKhYS5mJBs',
    appId: '1:849111596971:android:9f7a3f69c59818ac7e1cee',
    messagingSenderId: '849111596971',
    projectId: 'my-saathi-app',
    storageBucket: 'my-saathi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6CXIA_YpLBeOjKN55Ppjw8bO9ZqsOlsg',
    appId: '1:849111596971:ios:1ea7c2389825fa537e1cee',
    messagingSenderId: '849111596971',
    projectId: 'my-saathi-app',
    storageBucket: 'my-saathi-app.firebasestorage.app',
    iosBundleId: 'com.saathi.saathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6CXIA_YpLBeOjKN55Ppjw8bO9ZqsOlsg',
    appId: '1:849111596971:ios:1ea7c2389825fa537e1cee',
    messagingSenderId: '849111596971',
    projectId: 'my-saathi-app',
    storageBucket: 'my-saathi-app.firebasestorage.app',
    iosBundleId: 'com.saathi.saathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU4hVQ63CXfQPrjoj9fUGg4uN-C8pJ7HQ',
    appId: '1:849111596971:web:ddd316f566e59cd07e1cee',
    messagingSenderId: '849111596971',
    projectId: 'my-saathi-app',
    authDomain: 'my-saathi-app.firebaseapp.com',
    storageBucket: 'my-saathi-app.firebasestorage.app',
  );

}