import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart';
import 'core/di/injection.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/presentation/bloc/auth_bloc.dart';
import 'features/auth/presentation/bloc/auth_event.dart';
import 'features/onboarding/presentation/bloc/onboarding_bloc.dart';

// IMPORTANT: Requires firebase_options.dart generated by flutterfire configure
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // NOTE: Uncomment when Firebase CLI generates firebase_options.dart
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Using a stub for now so the app runs without crashing if not configured,
  // but it needs the real config for the functionality to work.
  try {
    await Firebase.initializeApp();
  } catch (e) {
    debugPrint('Firebase initialization warning: \${e.toString()}');
  }

  configureDependencies();

  runApp(const SaathiApp());
}

class SaathiApp extends StatelessWidget {
  const SaathiApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(
          create: (_) => getIt<AuthBloc>()..add(CheckAuthStatusEvent()),
        ),
        BlocProvider(create: (_) => getIt<OnboardingBloc>()),
      ],
      child: MaterialApp(
        title: 'Saathi',
        theme: AppTheme.darkTheme,
        home: const Scaffold(
          body: Center(child: Text('Saathi App Initialized')),
        ),
      ),
    );
  }
}
